FROM netflixoss/eureka:1.1.147
MAINTAINER Fargo dev team https://github.com/athlum/fargo

ADD eureka-client-test.properties /tomcat/webapps/eureka/WEB-INF/classes/eureka-client-test.properties
ADD eureka-server-test.properties /tomcat/webapps/eureka/WEB-INF/classes/eureka-server-test.properties
